Dynamically load and cache keyboard layout
osfans/trime pull request #1223
Opened 2024-02-03 17:40 UTC by nopdan

## Pull request

动态加载并缓存键盘布局，废弃 `style/keyboards` 选项。

优点：
- 方便
- 减少内存占用
- 加快主题加载、切换速度

缺点：
- 第一次切换到未使用过的布局会慢一点

其他待办：
- [x] 修复 `import_preset` 失效
- [ ] 修复切换横屏导致的布局异常
- [ ] 。。。

#### Issue tracker
Fixes will automatically close the related issues

Fixes #

#### Feature
Describe features of pull request

#### Code of conduct
- [ ] [CONTRIBUTING](CONTRIBUTING.md)

#### Style lint
- [ ] `make sytle-lint`

#### Build pass
- [ ] `make debug`

#### Manually test
- [ ] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub action ci pass
4. At least one contributor reviews and votes
5. Can be merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

#### Additional Info

2024-02-04 02:11 UTC, nopdan commented
before: ![264f7586d376b8d5c9ac733b74c451c6](https://github.com/osfans/trime/assets/47845580/cb46ec2d-1f89-451d-89b7-fd33bd8d4974)
after: ![38227a9008e23ad6ff515ec08f9a454b](https://github.com/osfans/trime/assets/47845580/4cf30bfe-342c-4ba3-a6f4-6f2814e10110)

2024-02-04 03:52 UTC, nopdan commented
https://github.com/osfans/trime/assets/47845580/e71026a9-a4d9-4746-8c54-02f5d58a5aee

2024-02-04 05:27 UTC, WhiredPlanck requested changes

2024-02-04 05:27 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/core/Trime.kt
> +        if (isChanged) initKeyboard()
这里冗余了，`onSystemNightModeChange` 会调用 `fireChange`，`fireChange` 会调用 `OnThemeChangeListener` 监听器。Trime 服务已经实现了这个监听器：

https://github.com/osfans/trime/blob/d814b1836ea22486837e1a32025e3445064333b3/app/src/main/java/com/osfans/trime/ime/core/Trime.kt#L114-L120

2024-02-04 05:27 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/keyboard/KeyboardSwitcher.kt
> +        if (alphabet.replace(Regex("""[a-z]"""), "").isEmpty()) {
```suggestion
        if (alphabet.matches("^[a-z]+$".toRegex())) {
```
下方类似

2024-02-04 05:57 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/keyboard/KeyboardSwitcher.kt
> +        }
从 122 行开始可以写成如下形式：

```kotlin
val layout = if (...) {
......
}
.takeIf { it in allKeyboardIds } 
    ?: "default"
    .also { Timber.d(...) }
```
甚至 `val layout = `  可以直接替换成 `return`

2024-02-04 06:18 UTC, nopdan commented on app/src/main/java/com/osfans/trime/ime/keyboard/KeyboardSwitcher.kt
> +        }
代码风格问题，没有影响（不太习惯这种写法

2024-02-06 04:29 UTC, goofyz commented
原本可以秒切換佈局。
現在這版本會有一秒左右的延遲。快速不斷按「切換鍵盤」的話，會令整個鍵盤沒有反應，要等它 load 完才回復正常。

2024-02-06 04:38 UTC, nopdan commented
> 原本可以秒切換佈局。 現在這版本會有一秒左右的延遲。快速不斷按「切換鍵盤」的話，會令整個鍵盤沒有反應，要等它 load 完才回復正常。

奇怪，我这边没法复现，一直都是秒切的。你具体是用的哪个版本呢，是ci还是自己编译的？

2024-02-06 06:45 UTC, goofyz commented
> > 原本可以秒切換佈局。 現在這版本會有一秒左右的延遲。快速不斷按「切換鍵盤」的話，會令整個鍵盤沒有反應，要等它 load 完才回復正常。
> 
> 奇怪，我这边没法复现，一直都是秒切的。你具体是用的哪个版本呢，是ci还是自己编译的？

自己編的和 ci 都試過，一樣慢。
可能機子有點舊 (pixel 4a)?

2024-02-06 06:55 UTC, nopdan commented
> > > 原本可以秒切換佈局。 現在這版本會有一秒左右的延遲。快速不斷按「切換鍵盤」的話，會令整個鍵盤沒有反應，要等它 load 完才回復正常。
> > 
> > 
> > 奇怪，我这边没法复现，一直都是秒切的。你具体是用的哪个版本呢，是ci还是自己编译的？
> 
> 自己編的和 ci 都試過，一樣慢。 可能機子有點舊 (pixel 4a)?

那就折中一下，默认缓存 `style/keyboards` 里的所有布局，不在里面的再动态加载。

2024-02-06 07:16 UTC, nopdan commented
@goofyz 我发现问题了，https://github.com/osfans/trime/pull/1223/commits/5362031eb7ee1403000a8a8d850b2369dc29c2ae 这个提交导致的，动态加载键盘应该没问题，你可以试试之前的提交https://github.com/osfans/trime/pull/1223/commits/d525dd2b89dd58867e19fa969b63818946a1ca90

2024-02-06 08:03 UTC, nopdan commented
> > > 原本可以秒切換佈局。 現在這版本會有一秒左右的延遲。快速不斷按「切換鍵盤」的話，會令整個鍵盤沒有反應，要等它 load 完才回復正常。
> > 
> > 
> > 奇怪，我这边没法复现，一直都是秒切的。你具体是用的哪个版本呢，是ci还是自己编译的？
> 
> 自己編的和 ci 都試過，一樣慢。 可能機子有點舊 (pixel 4a)?

之前快是因为没有切换 `ascii_mode`, 这是个 bug。现在修复后自然慢了，要调用 jni 的
___
可以试试在相同 `ascii_mode` 之间切换是否正常

2024-02-06 08:35 UTC, goofyz commented
這個 d525dd2b89dd58867e19fa969b63818946a1ca90 可以秒切換。

---
> 之前快是因为没有切换 ascii_mode, 这是个 bug。现在修复后自然慢了，要调用 jni 的

「之前」你是指現在 `develop` branch 上的現狀嗎？

2024-02-06 08:37 UTC, nopdan commented
> 這個 [d525dd2](https://github.com/osfans/trime/commit/d525dd2b89dd58867e19fa969b63818946a1ca90) 可以秒切換。
> 
> > 之前快是因为没有切换 ascii_mode, 这是个 bug。现在修复后自然慢了，要调用 jni 的
> 
> 「之前」你是指現在 `develop` branch 上的現狀嗎？

是的。

2024-02-06 12:35 UTC, goofyz commented
若用 new thread/coroutine call jni 可行否？應該 call jni 和切換鍵盤的所需時間差不多

2024-02-06 14:54 UTC, WhiredPlanck approved these changes

2024-02-06 17:15 UTC, nopdan commented
> 若用 new thread/coroutine call jni 可行否？應該 call jni 和切換鍵盤的所需時間差不多

我把 `ascii_mode` 的修改拆出来吧，这个问题还得想想

2024-02-07 04:54 UTC, Bambooin approved these changes

2024-02-07 04:55 UTC, merged