fix: use unified landscape mode
osfans/trime pull request #1413
Opened 2024-06-27 08:58 UTC by unlsycn

## Pull request

#### Feature
[文档](https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3)中有「横屏模式」的概念，#1191 添加了Landscape Keyboard，但是「横屏模式」的含义并不清晰，也不能很好地适配折叠屏等设备。这个PR将Landscape Mode设置项应用到其他使用横屏布局的判断中（除了`onEvaluateFullscreenMode`没有更改），在设置了「启用横屏模式」，`keyboardSidePadding`等参数将会使用对应横屏模式的值（这也与文档中的描述一致）。

这样的设置主要考虑了以下几种设备：
- 普通手机：竖屏时屏幕宽度较窄，横屏时较宽，需要不同的键盘设置，这里设为`AUTO`或`LANDSCAPE`都可以正常在横竖屏中切换。
- 平板：竖屏或横屏时屏幕宽度都较宽，如果横竖屏需要不同的键盘设置，设为`LANDSCAPE`，否则设为`AUTO`会使用竖屏设置，设为`NEVER`会使用横屏设置。
- 折叠屏手机：折叠时和普通手机一致，展开时横竖屏比例较为接近，设为`AUTO`可以使展开状态和横屏使用横屏设置，折叠状态竖屏使用竖屏设置。
- 竖折屏手机：展开时和普通手机一致，折叠时无论横屏和竖屏屏幕宽度都较窄，但折叠时应该没有使用输入法的需求。

#### Code of conduct
- [x] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [ ] `make sytle-lint`
- [x] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [x] `make debug`

#### Manually test
- [x] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

#### Additional Info
设置项的名称改变会导致此设置被重置，此外PR改变了现有设置的逻辑，可能需要更多讨论。

2024-06-27 14:20 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/composition/Composition.kt
> +        get() = if (appContext.isLandscapeMode()) theme.generalStyle.layout.stickyLinesLand
view 自带 context，除非确实没有 context 也无法传入 context，否则不要优先使用全局 appContext

2024-06-27 15:11 UTC, WhiredPlanck requested changes

2024-06-27 15:11 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/composition/Composition.kt
> +        get() = if (appContext.isLandscapeMode()) theme.generalStyle.layout.stickyLinesLand
view 自带 context，除非确实没有 context 也无法传入 context，否则不要优先使用全局 appContext

2024-06-27 15:11 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/core/InputView.kt
> +                if (appContext.isLandscapeMode()) keyboardSidePaddingLandscape else keyboardSidePadding
同上

2024-06-27 15:11 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/core/InputView.kt
> +                if (appContext.isLandscapeMode()) keyboardBottomPaddingLandscape else keyboardBottomPadding
同上

2024-06-28 01:26 UTC, unlsycn commented on app/src/main/java/com/osfans/trime/ime/composition/Composition.kt
> +        get() = if (appContext.isLandscapeMode()) theme.generalStyle.layout.stickyLinesLand
好的，谢谢。我对代码不太熟悉:D

2024-06-29 12:07 UTC, WhiredPlanck approved these changes

2024-06-29 12:41 UTC, Bambooin commented
Please use `./gradlew spotlessApply` to format your code.

2024-06-30 01:11 UTC, unlsycn commented
> Please use `./gradlew spotlessApply` to format your code.

Done.

2024-06-30 01:55 UTC, merged