fix: timing sync
osfans/trime pull request #1441
Opened 2024-07-30 04:23 UTC by gshang2017

## Pull request

#### Issue tracker
Fixes will automatically close the related issues

Fixes #
Fixes #

#### Feature
Describe features of this pull request

#### Code of conduct
- [ ] [CONTRIBUTING](CONTRIBUTING.md)

#### Code style
- [ ] `make sytle-lint`
- [ ] [Conventional Commits](https://www.conventionalcommits.org/)

#### Build pass
- [ ] `make debug`

#### Manually test
- [ ] Done

#### Code Review
1. No wildcards import
2. Manual build and test pass
3. GitHub Action CI pass
4. At least one contributor review and approve
5. Merged clean without conflicts
6. PR will be merged by rebase upstream base

#### Daily build
Login and download artifact at https://github.com/osfans/trime/actions

#### Additional Info

2024-08-10 05:00 UTC, WhiredPlanck requested changes

2024-08-10 05:00 UTC, WhiredPlanck commented on app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt
> +            }
请把条件判断去除。IntentReceiver 是多用途的

2024-08-10 06:16 UTC, gshang2017 commented on app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt
> +            }
已去除。

2024-08-13 03:15 UTC, WhiredPlanck approved these changes

2024-08-13 12:13 UTC, merged